-- 通知发送与尝试记录使用独立表，后台工作在事务提交后调用外部平台。
ALTER TABLE notification
  ADD COLUMN source_occurrence_id varchar(100) DEFAULT NULL COMMENT '源定时触发记录；其他业务通知为空',
  ADD COLUMN initiator_user_id varchar(100) DEFAULT NULL COMMENT '发起人；历史及系统通知可为空',
  ADD UNIQUE KEY uk_notification_recipient (enterprise_id, user_id, id),
  ADD UNIQUE KEY uk_notification_occurrence (enterprise_id, source_occurrence_id, user_id),
  ADD CONSTRAINT fk_notification_occurrence FOREIGN KEY (enterprise_id, source_occurrence_id) REFERENCES scheduled_occurrence(enterprise_id, id),
  ADD CONSTRAINT fk_notification_initiator FOREIGN KEY (initiator_user_id) REFERENCES app_user(id);

CREATE TABLE notification_delivery (
  id varchar(100) NOT NULL,
  enterprise_id varchar(100) NOT NULL,
  notification_id varchar(100) NOT NULL,
  recipient_user_id varchar(100) NOT NULL,
  connection_id varchar(100) NOT NULL,
  credential_revision bigint NOT NULL COMMENT '创建时的应用凭据版本，更换凭据后旧发送不得直接继续',
  delivery_reason varchar(24) NOT NULL COMMENT 'automatic 自动业务通知、scheduled 定时通知、test 管理员测试通知',
  binding_id varchar(100) DEFAULT NULL COMMENT '创建发送时锁定的绑定；未绑定而被阻止的记录为空',
  binding_revision bigint DEFAULT NULL COMMENT '创建发送时的绑定控制版本',
  provider_request_id varchar(50) COLLATE utf8mb4_bin NOT NULL COMMENT '每条发送固定一个随机编号，飞书使用此值去重',
  payload_json json DEFAULT NULL COMMENT '固定的已渲染请求，不含令牌或密钥；只清理终态过期内容',
  payload_hash char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '规范化请求内容的摘要，重试不得改内容',
  status varchar(24) NOT NULL DEFAULT 'pending' COMMENT 'pending、sending、retry_wait、accepted、failed、blocked、cancelled、unknown、expired',
  attempt_count int NOT NULL DEFAULT 0 COMMENT '实际准备发起网络请求的累计次数，不是工作领取次数',
  max_attempts int NOT NULL DEFAULT 5 COMMENT '自动尝试总上限，显式人工重试时可按规则增加一次',
  manual_retry_count int NOT NULL DEFAULT 0 COMMENT '首期同一发送最多人工重试三次',
  dispatch_generation int NOT NULL DEFAULT 1 COMMENT '人工重试时递增，用于区分新的后台工作',
  active_job_id varchar(100) DEFAULT NULL COMMENT '当前后台工作，阻止发送时可为空',
  next_attempt_at datetime(3) DEFAULT NULL,
  first_send_at datetime(3) DEFAULT NULL,
  retry_deadline_at datetime(3) DEFAULT NULL COMMENT '结果不确定时允许依赖平台去重自动重试的最后时刻',
  expires_at datetime(3) NOT NULL COMMENT '超过后不开始新的发送请求',
  provider_message_id varchar(191) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '平台实际返回的消息编号，不代表已读',
  accepted_at datetime(3) DEFAULT NULL COMMENT '平台确认接受本条消息的时间',
  last_error_code varchar(64) DEFAULT NULL,
  last_error_summary varchar(500) DEFAULT NULL COMMENT '不含请求内容、令牌及内部堆栈',
  revision bigint NOT NULL DEFAULT 1,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_delivery_enterprise (enterprise_id, id),
  UNIQUE KEY uk_delivery_notification (enterprise_id, notification_id, connection_id),
  UNIQUE KEY uk_delivery_provider_request (provider_request_id),
  KEY idx_delivery_due (status, next_attempt_at, id),
  KEY idx_delivery_connection (enterprise_id, connection_id, status, created_at, id),
  KEY idx_delivery_recipient (enterprise_id, recipient_user_id, created_at, id),
  KEY idx_delivery_binding (enterprise_id, connection_id, recipient_user_id, binding_id),
  CONSTRAINT fk_delivery_notification FOREIGN KEY (enterprise_id, recipient_user_id, notification_id) REFERENCES notification(enterprise_id, user_id, id),
  CONSTRAINT fk_delivery_connection FOREIGN KEY (enterprise_id, connection_id) REFERENCES enterprise_integration(enterprise_id, id),
  CONSTRAINT fk_delivery_binding FOREIGN KEY (enterprise_id, connection_id, recipient_user_id, binding_id) REFERENCES user_channel_binding(enterprise_id, connection_id, user_id, id),
  CONSTRAINT fk_delivery_job FOREIGN KEY (enterprise_id, active_job_id) REFERENCES background_job(enterprise_id, id),
  CONSTRAINT ck_delivery_status CHECK (status IN ('pending', 'sending', 'retry_wait', 'accepted', 'failed', 'blocked', 'cancelled', 'unknown', 'expired')),
  CONSTRAINT ck_delivery_attempts CHECK (attempt_count >= 0 AND max_attempts BETWEEN 1 AND 8 AND manual_retry_count BETWEEN 0 AND 3 AND dispatch_generation > 0),
  CONSTRAINT ck_delivery_reason CHECK (delivery_reason IN ('automatic', 'scheduled', 'test') AND credential_revision > 0),
  CONSTRAINT ck_delivery_binding_pair CHECK ((binding_id IS NULL AND binding_revision IS NULL) OR (binding_id IS NOT NULL AND binding_revision IS NOT NULL)),
  CONSTRAINT ck_delivery_ready CHECK (status NOT IN ('pending', 'sending', 'retry_wait') OR (binding_id IS NOT NULL AND payload_json IS NOT NULL AND payload_hash IS NOT NULL AND active_job_id IS NOT NULL)),
  CONSTRAINT ck_delivery_accepted CHECK (status <> 'accepted' OR accepted_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='一条通知通过一个外部接入发给一个成员的实际处理结果';

CREATE TABLE notification_delivery_attempt (
  id varchar(100) NOT NULL,
  enterprise_id varchar(100) NOT NULL,
  delivery_id varchar(100) NOT NULL,
  attempt_no int NOT NULL COMMENT '同一发送记录内递增的尝试序号',
  background_job_id varchar(100) NOT NULL,
  lease_version bigint NOT NULL COMMENT '本次领取工作时的租约版本，旧进程不得覆盖新结果',
  outcome varchar(32) NOT NULL DEFAULT 'started' COMMENT 'started、accepted、retryable_failure、permanent_failure、unknown',
  http_status int DEFAULT NULL COMMENT '实际取得的网络响应状态；未取得时为空',
  provider_code varchar(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '平台响应码，成功也记录实际值',
  provider_request_trace varchar(191) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '平台返回的排障编号，无返回则为空',
  error_code varchar(64) DEFAULT NULL,
  error_summary varchar(500) DEFAULT NULL COMMENT '脱敏错误原因',
  started_at datetime(3) NOT NULL,
  finished_at datetime(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_delivery_attempt (enterprise_id, delivery_id, attempt_no),
  KEY idx_delivery_attempt_retention (finished_at, id),
  CONSTRAINT fk_delivery_attempt_delivery FOREIGN KEY (enterprise_id, delivery_id) REFERENCES notification_delivery(enterprise_id, id),
  CONSTRAINT fk_delivery_attempt_job FOREIGN KEY (enterprise_id, background_job_id) REFERENCES background_job(enterprise_id, id),
  CONSTRAINT ck_delivery_attempt_number CHECK (attempt_no > 0 AND lease_version > 0),
  CONSTRAINT ck_delivery_attempt_outcome CHECK (outcome IN ('started', 'accepted', 'retryable_failure', 'permanent_failure', 'unknown')),
  CONSTRAINT ck_delivery_attempt_finished CHECK ((outcome = 'started' AND finished_at IS NULL) OR (outcome <> 'started' AND finished_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每次发送尝试的追加记录，网络结果未知时不得伪记为失败或成功';

ALTER TABLE background_job
  DROP CHECK ck_background_job_1,
  ADD CONSTRAINT ck_background_job_1 CHECK (kind IN ('run', 'document_parse', 'file_scan', 'mail', 'notification', 'event_publish', 'export', 'cleanup', 'scheduled_action', 'channel_delivery')),
  ADD KEY idx_background_kind_ready (kind, status, available_at, id),
  ADD KEY idx_background_kind_expired (kind, status, lease_until, id);

